---
- name: Create AWS EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: "Ansible-EC2"
        region: "{{ aws_region }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        key_name: "{{ key_name }}"
        security_groups: ["default"]
        network:
          assign_public_ip: yes
      register: ec2_instance

    - debug:
        var: ec2_instance
