---
- name: Network Automation with Ansible
  hosts: all
  gather_facts: no
  tasks:

    - name: Backup Network Configurations
      ansible.builtin.command:
        cmd: "scp admin@{{ inventory_hostname }}:/etc/network/interfaces /backup/{{ inventory_hostname }}_interfaces.bak"
      delegate_to: localhost
      run_once: true

    - name: Deploy Configuration to Network Devices
      ansible.builtin.template:
        src: templates/network_config.j2
        dest: /etc/network/interfaces
      notify: Restart Network Service

    - name: Validate Configuration
      ansible.builtin.command:
        cmd: "cat /etc/network/interfaces"
      register: config_output

    - name: Display Configuration Output
      ansible.builtin.debug:
        msg: "{{ config_output.stdout }}"

  handlers:
    - name: Restart Network Service
      ansible.builtin.service:
        name: networking
        state: restarted
