---
- name: Enforce s3 bucket versioning
  hosts: localhost
  gather_facts: false

  tasks:
    - name: List s3 buckets in the AWS account
      amazon.aws.s3_bucket_info:
      register: result 
    
    - debug:
        var: result.buckets

    - name: Enable versioning on s3 buckets
      amazon.aws.s3_bucket:
        name: "{{ item.name }}"
        versioning: 1
      loop: "{{ result.buckets }}"
