---
- name: "PLAY 1: First play, run through first"
  connection: local
  gather_facts: no
  become: no
  hosts: localhost
  tags: google, cloudflare
  vars:
    interfaces:
      my_first_var: "Ignition!"
  
  tasks:
    - name: "Task 1: SYS >> Ping out to define address: 127.0.0.1"
      shell: "ping 127.0.0.1 -c 3"
      register: ping_output

    - name: "Task 2: SYS >> Print out the ping results"
      debug:
        var: ping_output 
        
- name: "PLAY 2: Ping cloudflare.com when Tag is cloudflare"
  connection: local
  gather_facts: no
  become: no
  hosts: localhost
  tags: cloudflare  

  tasks:
  - name: "Task 1: SYS >> Ping out to define address: cloudflare.com"
    shell: "ping 1.1.1.1 -c 3"
    register: cloudflare_ping
  
  - name: "Task 2: SYS >> Print out the ping results"
    debug:
      msg: "{{ cloudflare_ping }}"


- name: "PLAY 3: Ping google.com when Tag is google"
  connection: local
  gather_facts: no
  become: no
  hosts: localhost
  tags: google

  tasks:
  - name: "Task 1: SYS >> Ping out to define address: google.com"
    shell: "ping 8.8.8.8 -c 3"
    register: google_ping

  - name: "Task 2: SYS >> Print out the ping results"
    debug:
      msg: "{{ google_ping }}"
