---
- name: Create and Configure EC2 Instances
  hosts: localhost
  connection: local

  tasks:
    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        key_name: "{{ key_name }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        instance_type: "t2.micro"
        security_groups: ["{{ security_group }}"]  # Must be a list
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        image_id: "{{ item.image }}"
        network_interfaces:
          - assign_public_ip: true
      loop:
        - { name: "server1", image: "{{ image_id_1 }}", os: "ubuntu" }
        - { name: "server2", image: "{{ image_id_2 }}", os: "ubuntu" }
        - { name: "server3", image: "{{ image_id_3 }}", os: "centos" }
